[package]
name = "pagerank"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
simple-pagerank = "0.2.0"

[[bin]]
name = "first_test"
path = "first_test.rs"
