# dineis to onoma tou step aristera kai meta apo poio eksartatai kai apo katw thn entolh
# ousiastika trexei mono thn prwth entolh alla epeidh auth exei anagkh thn epomenh h opoia me th
# seira ths exei thn paraepomenh alusidwta trexoun oles
# xwris pragmati h mia na xreiazetai thn allh

graph: graph_changes
	g++ graph.cpp -o graph.out

graph_changes: graph_mul
	g++ graph_changes.cpp -o graph_changes.out

graph_mul: find_max_node
	g++ graph_mul.cpp -o graph_mul.out

find_max_node:
	g++ find_max_node.cpp -o find_max_node.out
